spring.application.name=sunilies-shop
server.port=8080
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.web.resources.static-locations=classpath:/static/
# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sunilies.sg@gmail.com
spring.mail.password=fglojgrpygrejbxk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# Stringee Voice OTP
stringee.enabled=false
stringee.api-key-sid=
stringee.api-key-secret=
stringee.from-number=
stringee.access-token=
stringee.webhook-url=
# MoMo Sandbox (l?y t? developers.momo.vn)
momo.partner-code=MOMO
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.redirect-url=http://localhost:8080/payment/momo/return
momo.ipn-url=https://YOUR_NGROK_URL/payment/momo/ipn
#google gemini
gemini.enabled=true
gemini.api-key=AIzaSyBo7XG8yKYujUwD7g9rBjwSD6SgA4UwnxY
gemini.model=gemini-2.0-flash